djangoapp/blog/urls.py
from blog.views import index, page, post, created_by, category
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('post/<slug:slug>/', post, name='post'),
    path('page/<slug:slug>/', page, name='page'),
    path('created_by/<int:author_pk>/', created_by, name='created_by'),
    path('category/<slug:slug>/', category, name='category'),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from utils.rands import slugify_new
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse

class PostAttachment(AbstractAttachment):
    class Meta:
        verbose_name = "Post Attachment"
        verbose_name_plural = "Post Attachments"

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name

        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != str(self.file.name)
        
        if file_changed:
            resize_image(self.file, 900)

        return super_save

class Tag(models.Model):
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    name = models.CharField(
        max_length=100,
        )
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255,
        )
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(
        max_length=100,
        )
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255,
        )
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

class Page(models.Model):
    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"

    title = models.CharField(
        max_length=100,
        )
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255,
        )
    is_published = models.BooleanField(
        default=False,
        help_text=(
            "Este campo precisará estar marcado " \
            "para que a página seja exibida publicamente."
        )
    )
    content = models.TextField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by('-pk')

class Post(models.Model):
    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    objects = PostManager()

    title = models.CharField(
        max_length=100,
        )
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255,
        )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text=(
            "Este campo precisará estar marcado " \
            "para que o post seja exibido publicamente."
        )
    )
    content = models.TextField()
    cover = models.ImageField(
        upload_to='posts/%Y/%m/',
        blank=True,
        default='',
    )
    cover_in_post_content = models.BooleanField(
        default=False,
        help_text=(
            "Se marcado, a imagem de capa será exibida " \
            "dentro do conteúdo do post."
        )
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        )
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='post_created_by',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='post_updated_by',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        default=None,
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        default=None,
    )

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,)) 

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != str(self.cover.name)

        if cover_changed:
            resize_image(self.cover, 900)

        return super_save

djangoapp/blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from blog.models import Post

PER_PAGE = 9

def index(request):
    posts = Post.objects.get_published()

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'blog/pages/index.html',
        {
            'page_obj': page_obj,
        }
    )

def created_by(request, author_pk):
    posts = Post.objects.get_published().filter(
        created_by__pk=author_pk
    )

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'blog/pages/index.html',
        {
            'page_obj': page_obj,
        }
    )

def category(request, slug):
    posts = Post.objects.get_published().filter(
        category__slug=slug
    )

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'blog/pages/index.html',
        {
            'page_obj': page_obj,
        }
    )



def page(request, slug):
    return render(
        request,
        'blog/pages/page.html',
        {
            # 'page_obj': page_obj,
        }
    )


def post(request, slug):
     post = (
        Post.objects
        .get_published()
        .filter(slug=slug)
        .first()
     )

     return render(
        request,
        'blog/pages/post.html',
        {
            'post': post,
        }
    )

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        {% if page_obj %}
          <div class="card-grid">
            {% for post in page_obj %}
              {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
            {% endfor %}
          </div>
        {% else %}
          <div class="no-found center">
            <h1>Nada encontrado 😔</h1>
            <p>
              Não encontrei nada nesse link, por favor, clique em outro link
              ou vá para a 
              <a href="{% url 'blog:index' %}">Home</a>
            </p>
          </div>
        {% endif %}

      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">A page 😍</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium eaque placeat, optio architecto dignissimos est iure ipsum, iste doloribus dolorum nostrum veniam aspernatur adipisci eos et ab facilis, fugit labore!</p>
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
      <div class="single-post-cover pb-base">
        <img loading="lazy" src="{{ post.cover.url }}"
        alt="Cover do post {{ post.title }}">
      </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.title }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a
            class="post-meta-link" 
            href="{% url 'blog:created_by' post.created_by.pk %}"
            >
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name %}
                {{ post.created_by.first_name }} 
                {{ post.created_by.last_name }} 
              {% else %}
                {{ post.created_by.username }}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at|date:"d/m/Y \à\s H:i" }}
            </span>
          </span>
        </div>

        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" 
            href="{% url 'blog:category' post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{ post.category.name }}
              </span>
            </a>
          </div>
        {% endif %}

      </div>

      <p class="single-post-excerpt pb-base">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore, vero
        fugiat eum perferendis accusamus enim quos obcaecati. Voluptates a vel
        obcaecati ipsa in dignissimos facere odio et, ab provident assumenda!
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {% include 'blog/partials/_temp.html' %} 
      
        <div class="post-tags">
          <span>Tags: </span>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Testando</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Atenção</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Obrigado</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Educação</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Python</span>
          </a>

        </div>
        
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}